### ISSUE TITLE
Development of streamlit dashboard for Object Tracking and Counting

### ISSUE THREAD

**Issue by P-Pan089** [RizwanMunawar/yolov7-object-tracking#1]
Hello, i want to count specific classes on my Jetson Nano and visualize them on a streamlit dashboard but i am having major issues.
Could you please tell me when you will update this repository with the streamlit dashboard included?

**Comment by RizwanMunawar** [comment]
@P-Pan089, it will take time. But if you want soon, so you can approach me via LinkedIn and we can discuss things.

**Comment by RizwanMunawar** [comment]
@P-Pan089 You can check the code for streamlit dashboard with YOLOv5 from mentioned link below. https://github.com/RizwanMunawar/yolov5-object-tracking#streamlit-dashboard
