### ISSUE TITLE
Can we add detect pose and track for multiple humans

### ISSUE THREAD

**Issue by Ashes47** [RizwanMunawar/yolov7-object-tracking#12]

**Comment by RizwanMunawar** [comment]
@Ashes47! Yes you can add integration of pose with object tracking. But you will need to integrate both according to your use case by keeping in mind FPS, accuracy etc

**Comment by Ashes47** [comment]
Thanks for the prompt response. I think i will also try to have Detect and Track module separate so it's more modular. 🎉

**Comment by RizwanMunawar** [comment]
@Ashes47 Yes, you can do detection and tracking separate. As far as my understanding, it will easy manageable. If pose module will integrated, there will be lot of issue you can faced, and there will be lot of restrictions you need to take care.
