### ISSUE TITLE
Running on Google Colab

### ISSUE THREAD

**Issue by lorenzlorg** [RizwanMunawar/yolov7-object-tracking#13]
Running the code on Google Colab there's the following error:
`ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
`

I know that this error is related to the usage of Google Colab but it would be useful to have an executable notebook ready to test.

**Comment by RizwanMunawar** [comment]
@lorenzlorg! Sure, it was on the to-do list, soon it will be part of the code.

**Comment by RizwanMunawar** [comment]
@lorenzlorg! I have added *ready to use google colab* for repository and also fixed to issue you faced. You can find google colab from mentioned link below.
https://colab.research.google.com/drive/1xrB76UQ_LaVaBAxfTi8-a9dIcazmxD5b?usp=sharing
