### ISSUE TITLE
model file existed, but still to remote download

### ISSUE THREAD

**Issue by yangboz** [RizwanMunawar/yolov7-object-tracking#14]
py39yolov7,Macosx 10.15 
while 
```
python detect.py --weights yolov7.pt  --source ~/Videos/football1.mp4
```
it throwns:
```
ls yolov7.pt 
yolov7.pt
(py39yolov7) apple@appledeMacBook-Pro yolov7-object-tracking % python detect_and_track.py --weights yolov7.pt  --source ~/Videos/football1.mp4
Namespace(weights=['yolov7.pt'], download=True, source='/Users/apple/Videos/football1.mp4', img_size=640, conf_thres=0.25, iou_thres=0.45, device='', view_img=False, save_txt=False, save_conf=False, nosave=False, classes=None, agnostic_nms=False, augment=False, update=False, project='runs/detect', name='object_tracking', exist_ok=False, no_trace=False, colored_trk=False, save_bbox_dim=False)
Model weights not found. Attempting to download now...
```

**Comment by RizwanMunawar** [comment]
@yangboz! I have added the parameters to restrict downloads. You can use mentioned command below to avoid this.
```
python detect.py --weights yolov7.pt  --source ~/Videos/football1.mp4 --no-download
```

**Comment by yangboz** [comment]
> @yangboz! I have added the parameters to restrict downloads. You can use mentioned command below to avoid this.
> 
> ```
> python detect.py --weights yolov7.pt  --source ~/Videos/football1.mp4 --no-download
> 
> or 
> 
> python detect_and_track.py --weights yolov7.pt  --source ~/Videos/football1.mp4 --no-download
> ```

let me have a try again.thanks.

**Comment by RizwanMunawar** [comment]
@yangboz! Did ---no-download argument resolve the model again downloading issue?

**Comment by yangboz** [comment]
yes.thank you .
