### ISSUE TITLE
MOT output format

### ISSUE THREAD

**Issue by lorenzlorg** [RizwanMunawar/yolov7-object-tracking#15]
Using the parameter **--save-txt** it is possible to store _Normalize coordinates_. Is there a way to store these coordinates in the _classical format_, such as: https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/blob/main/track.py#:~:text=%23%20Write%20MOT%20compliant,%2C%20i)), so in this way: 
![image](https://user-images.githubusercontent.com/36056444/203126731-94d50f3c-9b6c-468e-a709-2b0c2f30bd93.png)

**Comment by lorenzlorg** [comment]
@RizwanMunawar In your opinion, this approach could be correct in order to obtain not normalized coordinates?
![image](https://user-images.githubusercontent.com/36056444/203135248-b485e5ea-438e-4788-a286-35bad1505db0.png)

**Comment by RizwanMunawar** [comment]
@lorenzlorg! Yes you can convert the YOLO format value to opencv format by using the link below.
https://stackoverflow.com/a/67097124

You will Just need to sort the bounding box to frame width and heights values, it will provide you classical values, that you can use for any backend work for applications

**Comment by lorenzlorg** [comment]
@RizwanMunawar sorry but I'm doing other tests and I'm a little confused.

The coordinates (scaled) **track.centroidarr[-1][0] / im0.shape[1]** and **track.centroidarr[-1][1] / im0.shape[0]** indicate the center of the object detected or something different?

https://github.com/RizwanMunawar/yolov7-object-tracking/blob/main/detect_and_track.py#:~:text=txt_str%20%2B%3D%20%22%25i%20%25i%20%25f%20%25f%22%20%25%20(track.id%2C%20track.detclass%2C%20track.centroidarr%5B%2D1%5D%5B0%5D%20/%20im0.shape%5B1%5D%2C%20track.centroidarr%5B%2D1%5D%5B1%5D%20/%20im0.shape%5B0%5D)
