### ISSUE TITLE
Sort ID, labels and Bounding Boxes are not working if you have more than 1 stream

### ISSUE THREAD

**Issue by faizelkDatapost** [RizwanMunawar/yolov7-object-tracking#16]
I have a streams.txt file which contains two videos and both videos play but no bounding boxes, labels and no unique id's are drawn. But it works perfect with one video.

I run script like this:
python3 detect_and_track.py  --source streams.txt --view-img

i think maybe the variables these variables ( dets_to_sort | tracked_dets | tracks)
are overwritten and by the time imshow happens it appends on wrong stream/frame

**Comment by RizwanMunawar** [comment]
@faizelkDatapost! Multi streams object tracking is not supported yet, I am working on this module, but it will take some time.
I am closing this issue for now, as it's an enhancement of the current code, not any issue in the code. 

Feel free to open a new issue, If you will face any errors.

**Comment by faizelkDatapost** [comment]
@RizwanMunawar Thank you. Appreciate the feedback
