### ISSUE TITLE
thresholds values validation vs inference #639

### ISSUE THREAD

**Issue by lorenzlorg** [RizwanMunawar/yolov7-object-tracking#18]
I've **trained** YOLOv7 on a custom dataset and then I **validated** it on test data using _test.py_ using default values for conf-thres (0.001) and iou-thres (0.65). I've obtained good results in mAP@0.5.

Now I was trying to use my YOLOv7 weights to make some **inferences**, on new images/videos, in particular I'm using YOLOv7+SORT to track pedestrians.

**It does make sense to consider a higher conf-thres in _detect_and_track.py_ in order to obtain more accurate results. Or should I use the same threshold values used in the validation phase?**

**Comment by RizwanMunawar** [comment]
@lorenzlorg! If you need the exact accuracy you get for the validation phase, then yes you should need to use the same threshold. Otherwise, you can test the model on videos and change the threshold with the hit and trails method, which can provide you with good results.

**Comment by lorenzlorg** [comment]
@RizwanMunawar thanks for your reply. 

Since the videos on which I'm making inferences are not annotated I think that my situation is the second one you mentioned. I've trained my YOLOv7 model on a custom dataset similar to my inference videos and then I'll change a little the thresholds.

I'm thinking that tuning these thresholds since I have two different datasets, one for training and validation and one for making inferences and experiments, could be reasonable at this point. 

In case of the same kind of datasets for the training/validation and inferences using the same thresholds could be more reasonable. I hope it makes sense. 

Thanks again

**Comment by RizwanMunawar** [comment]
@lorenzlorg Yes. You can test different thresholds and can see if the results differ and then you can compare them or change the threshold in such a way that can provide you with good results.

**Comment by RizwanMunawar** [comment]
@lorenzlorg! I am closing this issue for now. Feel free to open a new one If you will face any issues. Thanks

**Comment by lorenzlorg** [comment]
> @lorenzlorg! I am closing this issue for now. Feel free to open a new one If you will face any issues. Thanks

thanks a lot !
