### ISSUE TITLE
No person detected 

### ISSUE THREAD

**Issue by Debojyoti7** [RizwanMunawar/yolov7-object-tracking#19]
Hi I have tried the test code with 3 different videos but there is no detection or tracking n the runs folder video output. Any inputs if im doing anything wrong.

**Comment by RizwanMunawar** [comment]
@Debojyoti7! Your issue has been resolved. Coz you directly discussed with me the issue on LinkedIn.
I am closing this issue, for now, feel free to open a new issue if you will face some issues in the code.

**Comment by Harsh-Vavaiya** [comment]
@RizwanMunawar @Debojyoti7  I'm facing the same issue, can you please discuss the solution here?
