### ISSUE TITLE
Tracking non-movement objects

### ISSUE THREAD

**Issue by TinBarbie** [RizwanMunawar/yolov7-object-tracking#2]
Hi Mr.RizwanMunawar,
This is such a really great work and helpful to me.
For some reasons, I have been testing this on several random videos and I found that it can't track non-movement objects (but it retracks when the objects start to move). May I have an answer for this? And how can I do to keep tracking the objects when they don't move?
Many thanks

**Comment by RizwanMunawar** [comment]
Hi @TinBarbie! Thanks
When object will start moving or for non-movement objects, increase in size of training samples can decrease retracking. There are various other factors i.e. camera angle, video resolution, video quality etc, but these can be consider as a minor issues.
