### ISSUE TITLE
Instructions on how it works with Videos team?

### ISSUE THREAD

**Issue by enod-bataa** [RizwanMunawar/yolov7-object-tracking#20]
Hi, 

You mentioned there is support for `Video/WebCam/External Camera/IP Stream Supported` however, from the codebase, I don't see how it works with webcam, IP stream etc. 

Could you give us an instructions on how can I connect the code with external camera? Or do we simply have to store camera stream as images or video to locally first and then point out?

**Comment by RizwanMunawar** [comment]
@enod-bataa! 

- If you want to run object tracking with an external camera, you can use mentioned command below.

`python detect_and_track.py --weights yolov7.pt --source 1`

- If you want to run object tracking with a laptop camera, you can use mentioned command below.

`python detect_and_track.py --weights yolov7.pt --source 0`

- If you want to run object tracking on a live IP Camera stream (Ip Stream URL Format i.e "rtsp://username:pass@ipaddress:portno/video/video.amp), you can use mentioned command below.

`python detect_and_track.py --weights yolov7.pt --source "IP camera stream URL" `

**Comment by enod-bataa** [comment]
Thanks this is great!
