### ISSUE TITLE
Raspberry Pi Camera 

### ISSUE THREAD

**Issue by kushal140** [RizwanMunawar/yolov7-object-tracking#21]
Did you try this on Raspberry Pi 4 ?

**Comment by RizwanMunawar** [comment]
@kushal140! I have not yet tested the code on System and Jetson Nano.

**Comment by RizwanMunawar** [comment]
@kushal140 I am closing this issue for now as it's a question, not an issue. I would recommend you ask your queries in the Discussion section.
The discussions section is available at the mentioned link below.
https://github.com/RizwanMunawar/yolov7-object-tracking/discussions
