### ISSUE TITLE
Tracking is not efficient.

### ISSUE THREAD

**Issue by aarushi-sahu** [RizwanMunawar/yolov7-object-tracking#27]
Hello @RizwanMunawar, I  am stuck with this issue, Please help me out. 
Multiple object ids are being assigned to the same object. As per my knowledge, this is happening in cases where the object was occluded or multiple objects are present in close distance or when there is a flicker or change in frame position. Kindly help me resolve the issue or let me know if any way to bypass such issues. I am looking for an efficient way to track moving objects from a moving camera feed (recorded video).

**Comment by RizwanMunawar** [comment]
@aarushi-sahu!

This is due to the geometry of the image. you have a 2d image, so the Z plane coordinated will be plotted at top of the x or y coordinate. To reduce this issue, you will need to add identification with tracking or use some other tracking algorithm.
