### ISSUE TITLE
The tutorial doesnt work in all types of laptops

### ISSUE THREAD

**Issue by jsaray** [RizwanMunawar/yolov7-object-tracking#28]
Hi,

Thanks for your tutorial.
I tried your code  in my office laptop with a GPU and CPU and I couldn´t see any detections.

I tried it in my home laptop with a CPU only and I could indeed see your software working.

Today I retried on my office laptop with this instruction: ( I add the cpu parameter )

 python3.10 detect_and_track.py --weights yolov7.pt --source 0 --device cpu

And I could indeed see your software working.
For sure is nothing to do with your code (more like a GPU config issue). But maybe you can add some message to help the user understand what is happening.

See you and thank you again.

**Comment by RizwanMunawar** [comment]
Hi Jsaray! GPU modules can make some issues. I assume its half precision issue. I will resolve it ASAP.
Thanks.
