### ISSUE TITLE
how can train your model with my custom datasets?

### ISSUE THREAD

**Issue by samrand-majnooni** [RizwanMunawar/yolov7-object-tracking#3]
hi I have very big labeled dataset of birds and want track bird. how can your model help me? it possible pretrain your model with my dataset? please give me a example.

**Comment by RizwanMunawar** [comment]
@samrand-majnooni !Yes you can train model on your custom data by following the tutorial [Train YOLOv7 on custom data](https://medium.com/augmented-startups/yolov7-training-on-custom-data-b86d23e6623). After training you can utilize your custom trained model with object tracking code.

**Comment by RizwanMunawar** [comment]
I am closing this issue, as there is no update on this further. Feel free to open issue again, If you face any issue. Thanks

**Comment by charming2992** [comment]
> 

hi, I have trained my own dataset using yolov7. Then how can I ues your code to track them? Can you tell me where should edit. Thank you!
